### ISSUE TITLE
在配置数据库帐号和密码时显示config.db.user undefined

### ISSUE THREAD

**Issue by 353355756** [YMFE/yapi-cli#1]
在配置数据库密码时，显示如下错误：

yapi-cli/src/commands/server.js:38
    config.db.user = config.dbUser;
                   ^
TypeError: Cannot set property 'user' of undefined

把38行的代码修改为：
    data.db.user = config.dbUser;
    data.db.pass = config.dbPass;
希望修复。

**Comment by suxiaoxin** [comment]
@353355756 已修复，npm install -g yapi 安装下最新版（1.0.10）
感谢反馈！

**Comment by 353355756** [comment]
ok
