### ISSUE TITLE
handleNpmInstall 方法写死了 registry，而淘宝 registry 证书过期导致无法安装

### ISSUE THREAD

**Issue by hzfi** [YMFE/yapi-cli#20]
https://registry.npm.taobao.org 因为证书过期，无法下载

希望能够解决

**Comment by baihy-96** [comment]
我试的直接用npm install -g yapi-cli 不指定淘宝镜像 可以安装成功 你试试呢

**Comment by hzfi** [comment]
我直接下载好后改源码可以跑
