### ISSUE TITLE
可视化部署时，初始化数据库mongodb失败

### ISSUE THREAD

**Issue by chess297** [YMFE/yapi-cli#9]
- node :  v10.16.3
- mongodb : v4.2.3
错误信息：
> yapi-vendor@1.8.7 install-server /root/yapi/vendors > node server/install.js
Error: (node:27668) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor

应该是新版本mongodb 连接 useUnifiedTopology 参数需要设置。
因为不想降级mongodb，所以用命令行部署模式，修改了utils/db.js 22行为
```
 let options = {useNewUrlParser: true, useCreateIndex: true,useUnifiedTopology:true};
```

**Comment by chess297** [comment]
> * node :  v10.16.3
> * mongodb : v4.2.3
>   错误信息：
> 
> > yapi-vendor@1.8.7 install-server /root/yapi/vendors > node server/install.js
> > Error: (node:27668) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor
> 
> 应该是新版本mongodb 连接 useUnifiedTopology 参数需要设置。
> 因为不想降级mongodb，所以用命令行部署模式，修改了utils/db.js 22行为
> 
> ```
>  let options = {useNewUrlParser: true, useCreateIndex: true,useUnifiedTopology:true};
> ```

转到这里了：https://github.com/YMFE/yapi/issues/1605

**Comment by yeongjet** [comment]
#1607
